export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS'
export const LOAD_MOVIES_FAILURE = 'LOAD_MOVIES_FAILURE'

export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS'
export const DELETE_MOVIES_FAILURE = 'DELETE_MOVIES_FAILURE'