export const LOAD_TVSHOWS_SUCCESS = 'LOAD_TVSHOWS_SUCCESS'
export const LOAD_TVSHOWS_FAILURE = 'LOAD_TVSHOWS_FAILURE'

export const DELETE_TVSHOWS_SUCCESS = 'DELETE_TVSHOWS_SUCCESS'
export const DELETE_TVSHOWS_FAILURE = 'DELETE_TVSHOWS_FAILURE'

export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'